# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/code/clion/apue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/code/clion/apue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/code/clion/apue/CMakeFiles /var/code/clion/apue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/code/clion/apue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sh

# Build rule for target.
sh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sh
.PHONY : sh

# fast build rule for target.
sh/fast:
	$(MAKE) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/build
.PHONY : sh/fast

#=============================================================================
# Target rules for targets named cp

# Build rule for target.
cp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cp
.PHONY : cp

# fast build rule for target.
cp/fast:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/build
.PHONY : cp/fast

#=============================================================================
# Target rules for targets named getpid

# Build rule for target.
getpid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 getpid
.PHONY : getpid

# fast build rule for target.
getpid/fast:
	$(MAKE) -f CMakeFiles/getpid.dir/build.make CMakeFiles/getpid.dir/build
.PHONY : getpid/fast

#=============================================================================
# Target rules for targets named cp2

# Build rule for target.
cp2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cp2
.PHONY : cp2

# fast build rule for target.
cp2/fast:
	$(MAKE) -f CMakeFiles/cp2.dir/build.make CMakeFiles/cp2.dir/build
.PHONY : cp2/fast

#=============================================================================
# Target rules for targets named ls

# Build rule for target.
ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls
.PHONY : ls

# fast build rule for target.
ls/fast:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/build
.PHONY : ls/fast

src/intro/cp.o: src/intro/cp.c.o

.PHONY : src/intro/cp.o

# target to build an object file
src/intro/cp.c.o:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/intro/cp.c.o
.PHONY : src/intro/cp.c.o

src/intro/cp.i: src/intro/cp.c.i

.PHONY : src/intro/cp.i

# target to preprocess a source file
src/intro/cp.c.i:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/intro/cp.c.i
.PHONY : src/intro/cp.c.i

src/intro/cp.s: src/intro/cp.c.s

.PHONY : src/intro/cp.s

# target to generate assembly for a file
src/intro/cp.c.s:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/src/intro/cp.c.s
.PHONY : src/intro/cp.c.s

src/intro/cp2.o: src/intro/cp2.c.o

.PHONY : src/intro/cp2.o

# target to build an object file
src/intro/cp2.c.o:
	$(MAKE) -f CMakeFiles/cp2.dir/build.make CMakeFiles/cp2.dir/src/intro/cp2.c.o
.PHONY : src/intro/cp2.c.o

src/intro/cp2.i: src/intro/cp2.c.i

.PHONY : src/intro/cp2.i

# target to preprocess a source file
src/intro/cp2.c.i:
	$(MAKE) -f CMakeFiles/cp2.dir/build.make CMakeFiles/cp2.dir/src/intro/cp2.c.i
.PHONY : src/intro/cp2.c.i

src/intro/cp2.s: src/intro/cp2.c.s

.PHONY : src/intro/cp2.s

# target to generate assembly for a file
src/intro/cp2.c.s:
	$(MAKE) -f CMakeFiles/cp2.dir/build.make CMakeFiles/cp2.dir/src/intro/cp2.c.s
.PHONY : src/intro/cp2.c.s

src/intro/getpid.o: src/intro/getpid.c.o

.PHONY : src/intro/getpid.o

# target to build an object file
src/intro/getpid.c.o:
	$(MAKE) -f CMakeFiles/getpid.dir/build.make CMakeFiles/getpid.dir/src/intro/getpid.c.o
.PHONY : src/intro/getpid.c.o

src/intro/getpid.i: src/intro/getpid.c.i

.PHONY : src/intro/getpid.i

# target to preprocess a source file
src/intro/getpid.c.i:
	$(MAKE) -f CMakeFiles/getpid.dir/build.make CMakeFiles/getpid.dir/src/intro/getpid.c.i
.PHONY : src/intro/getpid.c.i

src/intro/getpid.s: src/intro/getpid.c.s

.PHONY : src/intro/getpid.s

# target to generate assembly for a file
src/intro/getpid.c.s:
	$(MAKE) -f CMakeFiles/getpid.dir/build.make CMakeFiles/getpid.dir/src/intro/getpid.c.s
.PHONY : src/intro/getpid.c.s

src/intro/ls.o: src/intro/ls.c.o

.PHONY : src/intro/ls.o

# target to build an object file
src/intro/ls.c.o:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/intro/ls.c.o
.PHONY : src/intro/ls.c.o

src/intro/ls.i: src/intro/ls.c.i

.PHONY : src/intro/ls.i

# target to preprocess a source file
src/intro/ls.c.i:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/intro/ls.c.i
.PHONY : src/intro/ls.c.i

src/intro/ls.s: src/intro/ls.c.s

.PHONY : src/intro/ls.s

# target to generate assembly for a file
src/intro/ls.c.s:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/src/intro/ls.c.s
.PHONY : src/intro/ls.c.s

src/intro/sh.o: src/intro/sh.c.o

.PHONY : src/intro/sh.o

# target to build an object file
src/intro/sh.c.o:
	$(MAKE) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/intro/sh.c.o
.PHONY : src/intro/sh.c.o

src/intro/sh.i: src/intro/sh.c.i

.PHONY : src/intro/sh.i

# target to preprocess a source file
src/intro/sh.c.i:
	$(MAKE) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/intro/sh.c.i
.PHONY : src/intro/sh.c.i

src/intro/sh.s: src/intro/sh.c.s

.PHONY : src/intro/sh.s

# target to generate assembly for a file
src/intro/sh.c.s:
	$(MAKE) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/intro/sh.c.s
.PHONY : src/intro/sh.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sh"
	@echo "... cp"
	@echo "... edit_cache"
	@echo "... getpid"
	@echo "... cp2"
	@echo "... ls"
	@echo "... src/intro/cp.o"
	@echo "... src/intro/cp.i"
	@echo "... src/intro/cp.s"
	@echo "... src/intro/cp2.o"
	@echo "... src/intro/cp2.i"
	@echo "... src/intro/cp2.s"
	@echo "... src/intro/getpid.o"
	@echo "... src/intro/getpid.i"
	@echo "... src/intro/getpid.s"
	@echo "... src/intro/ls.o"
	@echo "... src/intro/ls.i"
	@echo "... src/intro/ls.s"
	@echo "... src/intro/sh.o"
	@echo "... src/intro/sh.i"
	@echo "... src/intro/sh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

